### ISSUE TITLE
the pinksale  no good

### ISSUE THREAD

**Issue by Bamboozler89** [AuditRateTech/Smart-Contract-Audits#1]
the coin wont transfer it wont even allow me  to press the claim button

**Comment by CoryFeco** [comment]
All sales on Pinksale have a "Softcap" and "Hardcap" and a "Sale End Date".

The sale on Pinksale doesn't close until either"
A) The Hardcap (maximum token for sale) is met, or
B) The Softcap (minimum token that can be sold in order for the PreSale to complete) AND the "Sale End Date"

If A or B isn't met then all BNB will be refunded to the contributors at "Sale End Date"

This is how every Pinksale operates for every token sale
